# Functions
Function is a piece of reusable code aimed at solving a particular task.

### <span style="color:red">Built-in List Functions</span>

#### max() and min() built-in functions
max(list) --> Returns item from the list with max value.

min(list) --> Returns item from the list with min value.


In [3]:
fam = [1.73, 1.68, 1.71, 1.89] 

print (max(fam))
print (min(fam))

1.89
1.68


#### round() built-in function
number[, ndigits] --> Round a number to a given precision in decimal digits (default 0 digits).This always returns a floating point number.  Precision may be negative. [ ] means optional argument.

In [8]:
print round(1.68,1)
print round(1.68)

1.7
2.0


#### help() built-in function or ?object
class _Helper(__builtin__.object) --> Provides help on built in objects

?object --> ?round, ?max, etc.

help (round)

#### complex() built-in function
complex(real[, imag]) --> Create a complex number from a real part and an optional imaginary part. This is equivalent to (real + imag*1j) where imag defaults to 0.

In [17]:
print(complex(1.2,3))

(1.2+3j)


#### sorted (iterable, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customise the sort order, and the
    reverse flag can be set to request the result in descending order.
    
    key=None means that if you don't specify the key argument, it will be None. reverse=False means that if you don't specify the reverse argument, it will be False.

**Side Note: *iterable*:**
An object capable of returning its members one at a time. Examples of iterables include all sequence types (such as list, str, and tuple) and some non-sequence types like dict and file and objects of any classes you define with an __iter__() or __getitem__() method. Iterables can be used in a for loop and in many other places where a sequence is needed (zip(), map(), …). When an iterable object is passed as an argument to the built-in function iter(), it returns an iterator for the object. This iterator is good for one pass over the set of values. When using iterables, it is usually not necessary to call iter() or deal with iterator objects yourself. The for statement does that automatically for you, creating a temporary unnamed variable to hold the iterator for the duration of the loop

In [12]:
fam_sorted = sorted(fam, reverse=True)
print(fam_sorted)

[1.89, 1.73, 1.71, 1.68]


### <span style="color:red">Methods</span>
Methods are functions that can be applied to (belong to) objects.

#### Examples of Methods
Each object type has specific methods that could be applied to them:

str --> capitalize(), upper(), lower(), replace(), index()

float --> bit_length(), conjugate()

list --> index(), count(), append(), remove(), extend(), reverse()

In [53]:
# str object --> capitalize(), replace(), index()

sister = 'Liz'
print (sister.capitalize()) # Capitalizes first letter of the the string

print (sister.upper()) # Capitalizes the string

print (sister.replace('z','sa')) # Replaces the element in a string with another

print (sister.index('z')) # returns the index of the letter in the string

Liz
LIZ
Lisa
2


In [90]:
# list object --> index(), count(), append(), remove(), extend(), reverse(), insert()

print (fam_sorted.index(1.73)) # returns the index of an element in the list
print (fam_sorted.count(1)) # counts the number of time the argument appears in the list

1
0


In [92]:
fam = [1.73, 1.68, 1.71, 1.89] 
fam.append(1.82) # appends a passed obj into the existing list --adds an element 
print (fam) 

[1.73, 1.68, 1.71, 1.89, 1.82]


In [93]:
fam.extend([1.83,1.84]) # appends the contents of seq to list. The argument has to be iterable object (difference vs. append())
print (fam) 

[1.73, 1.68, 1.71, 1.89, 1.82, 1.83, 1.84]


In [95]:
fam.append([1.83,1.84]) # appends the sub-list to the list as an element
print (fam) 
fam.remove([1.83,1.84]) # removes the first element of a list that matches the input
print (fam) 

[1.73, 1.68, 1.71, 1.89, 1.82, 1.83, 1.84, [1.83, 1.84]]
[1.73, 1.68, 1.71, 1.89, 1.82, 1.83, 1.84]


In [96]:
fam.insert(6,1.90) # inserts object obj into a list at offset index.--insert(index,obj) --insert(len(list),obj) = = append(obj)
print (fam) 

[1.73, 1.68, 1.71, 1.89, 1.82, 1.83, 1.9, 1.84]


In [97]:
fam.reverse()  # reverses the order of the elements in the list
print (fam) 

[1.84, 1.9, 1.83, 1.82, 1.89, 1.71, 1.68, 1.73]


### <span style="color:red">Packages</span>
Packages are directories of Python Scripts and each script is a Module

- Modules contain specific functions, methods, types
- Thousands of packages available:
 - Numpy (arrays)
 - Pandas (data frames)
 - Matplotlib (data visualizations)
 - Scikit-learn (machine learning

#### Install packages: 
- http://pip.readthedocs.org/en/stable/installing/
- Download get-pip.py
- Terminal:
 - python3 get-pip.py
 - pip3 install numpy

In [84]:
import numpy as np #imports the numpy package --> np is an alias for the package
np.array([1, 2, 3])

array([1, 2, 3])

In [85]:
from numpy import array #if you need to use specific function from a package, just import that function
array([1, 2, 3]) # after that, you don't need to refer to the package anymore and can use the function directly

array([1, 2, 3])

In [88]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r*r

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.70176968209
Area: 0.580880481649


In [89]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
# radians() function converts angle in degrees to radians
dist = r*radians(12)

# Print out dist
print(dist)

40317.1057211
